project:
  name: audio-adversarial-detection
  time_format: "%Y-%m-%d-%H-%M-%S"
  model_name: "Resnet101"
  method: "WB"

data:
  train_json: "data/json_file/WB/data_train_WB.json"
  val_json: "data/json_file/WB/data_val_WB.json"
  num_workers: 16

train:
  batch_size: 16
  num_epochs: 25
  learning_rate: 0.0001
  weight_decay: 1e-5
  n_fft: 512
  sr: 16000
  attention_dim: 64
  num_classes: 2
  device: "cuda:1"
  best_acc: 0.90

model:
  save_dir: "best_model"